baseURL = "https://weihaozhou2008.github.io/"
languageCode = "zh-cn"
title = "Chorlin"

theme = "PaperMod"

[params]
  author = "Chorlin"
  description = "Mathematics · Physics · Thoughts"

  defaultTheme = "auto"

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  math = true

  [params.profileMode]
    enabled = false

[params.homeInfoParams]
  Title = "Chorlin"
  Content = """
弦不逐响，凛自成声

Mathematics · Physics · Thoughts
"""

[[menu.main]]
identifier = "math"
name = "Mathematics"
url = "/math/"
weight = 10

[[menu.main]]
identifier = "physics"
name = "Physics"
url = "/physics/"
weight = 20

[[menu.main]]
identifier = "essays"
name = "Essays"
url = "/essays/"
weight = 30

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 40