baseURL = "https://weihaozhou2008.github.io/"
languageCode = "zh-cn"
title = "秋凛离弦"

theme = "PaperMod"

[params]
  author = "秋凛离弦"
  description = "Mathematics · Physics · Thoughts"

  defaultTheme = "auto"

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  math = true

  env = "production"


[params.profileMode]
  enabled = true
  title = "秋凛离弦"
  subtitle = """
弦不逐响，凛自成声

Mathematics · Physics · Thoughts
"""
  imageUrl = "/images/avatar.png"
  imageTitle = "秋凛离弦"
  imageWidth = 160
  imageHeight = 160

  buttons = [
    { name = "Mathematics", url = "/math/" },
    { name = "Physics", url = "/physics/" },
    { name = "Essays", url = "/essays/" }
  ]


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/WeiHaoZhou2008"

[[params.socialIcons]]
  name = "link"
  url = "https://www.zhihu.com/people/martin-87-32"


[[menu.main]]
identifier = "math"
name = "Mathematics"
url = "/math/"
weight = 10


[[menu.main]]
identifier = "physics"
name = "Physics"
url = "/physics/"
weight = 20


[[menu.main]]
identifier = "essays"
name = "Essays"
url = "/essays/"
weight = 30


[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 40


[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50


[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 60


[outputs]
home = ["HTML", "RSS", "JSON"]